### ISSUE TITLE
error in opening webapp

### ISSUE THREAD

**Issue by rpotter12** [fossasia/meilix-generator#434] opened 2019-03-21 08:55 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/meilix

![Screenshot from 2019-03-21 14-23-55](https://user-images.githubusercontent.com/34352567/54741671-2f9e2c80-4be5-11e9-98bc-862494759db0.png)

**Comment by pranav1698** [comment] 2019-03-21 15:36
@rpotter12 the webapp must work after some time, this is because of heroku outages and can be checked by seeing one of the other generator sites:
![Screenshot from 2019-03-21 21-05-22](https://user-images.githubusercontent.com/34754265/54764076-14e7aa00-4c1d-11e9-8ff6-05d7be400f73.png)

**Comment by pranav1698** [comment] 2019-03-23 08:54
@xeon-zolt @meets2tarun please update us with the heroku logs

**Comment by pranav1698** [comment] 2019-04-01 15:27
@rpotter12 the webapp works now you can close this one

**Comment by nk521** [comment] 2019-04-15 16:34
@rpotter12 you can close this as now the issue is solved

**Closed** 2019-04-15 18:55 UTC
