### ISSUE TITLE
Make check your mail info more consistent with the app

### ISSUE THREAD

**Issue by tabesin** [fossasia/meilix-generator#249] opened 2018-10-05 08:47 UTC
**I'm submitting a ...**  (check one with "x")
- [x] feature request

**Actual Behaviour**
The current check your mail info page is inconsistent with the visual appearance of the app and also does not make sufficiently clear that it belongs to the meilix-generator.

**Expected Behaviour**
It should include the menu bar section of the Meilix app standard page.
It should apply the same CSS as the Meilix app.
The image should be replaced by a more intuitive picture e.g. showing a model inbox with the email you will receive.

**Steps to reproduce it**
Press "Build".

**Other information**

This may require to put the flask rendering of the menu into an own template in compliance with the Do not repeat yourself principle.

**Would you like to work on the issue?**

No.

**Comment by sk9331657** [comment] 2018-10-05 10:56
@tabesin  Can I work on it??

**Comment by sarnava1** [comment] 2018-10-05 21:55
@tabesin I cannot reproduce it. Nothing happens on  clicking the Build button!!

**Comment by sarnava1** [comment] 2018-10-06 04:03
@tabesin please help me in reproducing this. Since I am already familiar with the UI/UX I want to majorly contribute to the project.

**Comment by meets2tarun** [comment] 2018-10-06 10:59
>Nothing happens on clicking the Build button!!

@sarnava1 Sometimes build page doesn't work. Discussed majorly here #104.

Try again building, it will work.

Thanks

**Comment by sarnava1** [comment] 2018-10-17 20:15
@tabesin PR #289 solves this issue. You can close this now through PR #289

**Comment by meets2tarun** [comment] 2018-10-18 05:41
@sarnava1 
build button is broken and how do you check that the page appearing after the build button is similar to what has been mentioned here.

**Comment by sarnava1** [comment] 2018-10-18 15:12
@meets2tarun actually I built the layout for the pages through which I rendered all the pages. Since all the other pages were working fine I safely assumed that since everything was same for all the pages except the block for the body part then the build.html will also work fine. Then the build  button was not working. Now I went through the issues and the discussions following them and found that pranav is working in making the build button work. So once it is successful I will test that build.html page. But from working experience I can say that the build.html will work fine. Thanks a lot for reviewing and guiding so much.

**Comment by meets2tarun** [comment] 2018-10-18 16:31
Sure @sarnava1 
Let's see, go ahead

**Comment by sarnava1** [comment] 2018-10-23 11:08
This is the build page now:

![outputpageconsistent](https://user-images.githubusercontent.com/25319565/47353998-36c71a00-d6db-11e8-9a07-cbb02e7d79c6.png)

@meets2tarun and @tabesin I think this issue can be closed now through PR #289. Since the issue was to make build.html consistent with the existing UI of the page then the current build.html is consistent with the standard style. @meets2tarun I have attached the screenshot now.

**Comment by sarnava1** [comment] 2018-10-23 20:08
Please look into this @tabesin @meets2tarun

**Closed** 2018-10-24 12:09 UTC
Labels: has-PR
